
### Variables

@url = http://localhost:3000/api

@menuid = 664286a57856ef04bf877212

@eventid = 66428984f41f820123ad7461

@geteventid = 663186cf1ffbbff898dd9162

### GET Menu

GET {{url}}/menu

### Create a Menu Item

POST {{url}}/menu
Content-Type: application/json

{
   "name" : "Footlong Dog",
   "description" : "12 inch hotdog",
   "price" : "$15.99"

}

### Update menu item

PUT {{url}}/menu/{{menuid}}
Content-Type: application/json

{
   "name" : "brat",
   "description" : "German Brat.",
   "price" : "$17.99"

}

### Delete menu item

DELETE {{url}}/menu/{{menuid}}

### GET Events

GET {{url}}/events



### GET Event by ID

GET {{url}}/events/{{geteventid}}

### Create a Event 

POST {{url}}/events
Content-Type: application/json

{
   "name" : "Party with hotdogs",
   "location" : "Apppelton",
   "date" : "2024-06-15",
   "hours" : "1100-1700"
}

### Delete an Event

DELETE {{url}}/events/{{eventid}}